Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@franmacke 
franmacke
/
pong
Private
Code
Issues
Pull requests
Actions
Projects
Security
Insights
Settings
pong/.github/workflows/main.yml
@franmacke
franmacke Create main.yml
Latest commit 12c30c0 3 minutes ago
 History
 1 contributor
40 lines (36 sloc)  1.27 KB

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "test-build" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m unittest discover tests
    - name: pyinstaller Script.spec
      run: |
        pyinstaller Script.spec
You have unread notifications